# -*- coding: utf-8 -*-
"""Personal: AI (CV: Segmentation Semantic, Arboreal).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xP1z8IBJvA0jdB6qyEUjxRZTukDCKHQw
"""

# Installations
!pip install tensorflow==2.7.0
!pip install pixellib
!pip install -U pillow

# Imports
import pixellib
import matplotlib.pyplot as plt
from pixellib.instance import instance_segmentation
from pixellib.semantic import semantic_segmentation

# Variables
model = "//content//drive//MyDrive//Coding//Personal Projects//1: Artificial Intelligence//Resources//deeplabv3_xception_tf_dim_ordering_tf_kernels.h5"
input_image = "//content//drive//MyDrive//Coding//Personal Projects//1: Artificial Intelligence//Resources//OwlCamouflage.jpeg"
output_image = "//content//drive//MyDrive//Coding//Personal Projects//1: Artificial Intelligence//Resources//OwlCamouflage_Segmented.jpeg"

# Semantic Segmentation
segment_image = semantic_segmentation()
segment_image.load_pascalvoc_model(model)
segment_image.segmentAsPascalvoc(input_image,
       output_image_name = output_image, overlay = True)
plt.figure(figsize=(26, 18))
plt_image = plt.imread(output_image)
plt.imshow(plt_image)